# Generated by Django 4.2.7 on 2024-10-10 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationsObjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название объекта"
                    ),
                ),
                (
                    "name_tables",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Название для табеля"
                    ),
                ),
                (
                    "short_names",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Обиходные название"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Ближайший город"
                    ),
                ),
                (
                    "property_location",
                    models.TextField(
                        blank=True, verbose_name="Расположение объекта. Транспорт."
                    ),
                ),
                (
                    "pay_weekend",
                    models.BooleanField(default=False, verbose_name="Оплата выходных"),
                ),
                (
                    "pay_processing",
                    models.BooleanField(
                        default=False, verbose_name="Оплата переработки"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание объекта"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=150, unique=True, verbose_name="URL"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workers.organizationexploitation",
                        verbose_name="Эксплуатирующая организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект",
                "verbose_name_plural": "Объекты",
                "ordering": ["organization"],
                "permissions": (
                    ("organizationsObjects_add", "Объекты. Добавить."),
                    ("organizationsObjects_view", "Объекты. Просмотреть."),
                    ("organizationsObjects_delete", "Объекты. Удалить."),
                    ("organizationsObjects_change", "Объекты. Редактировать."),
                ),
                "default_permissions": "",
            },
        ),
    ]
