# Generated by Django 4.2.7 on 2023-12-07 09:51

import apps.workers.models.workers
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="Отдел"),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Сокращенное название"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Структура/Отдел",
                "verbose_name_plural": "Структура/Отделы",
                "ordering": ["pk"],
                "permissions": (
                    ("department_add", "Добавить."),
                    ("department_change", "Редактировать."),
                    ("department_delete", "Удалить."),
                    ("department_view", "Просмотреть."),
                ),
            },
        ),
        migrations.CreateModel(
            name="Subdivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="Управление/Подразделение",
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Сокращенное название"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Управление/Подразделение",
                "verbose_name_plural": "Управления/Подразделения",
                "ordering": ["pk"],
                "permissions": (
                    ("subdivision_add", "Добавить."),
                    ("subdivision_change", "Редактировать."),
                    ("subdivision_delete", "Удалить."),
                    ("subdivision_view", "Просмотреть."),
                ),
            },
        ),
        migrations.CreateModel(
            name="Chief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Должность"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Сокращенное название"
                    ),
                ),
                (
                    "rights",
                    models.IntegerField(
                        default=0, unique=True, verbose_name="Уровень доступа"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auth.group",
                        verbose_name="Группы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
                "ordering": ["rights"],
                "permissions": (
                    ("chief_add", "Добавить."),
                    ("chief_change", "Редактировать."),
                    ("chief_delete", "Удалить."),
                    ("chief_view", "Просмотреть."),
                ),
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("surname", models.CharField(max_length=60, verbose_name="Фамилия")),
                ("name", models.CharField(max_length=60, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(max_length=60, verbose_name="Отчество"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.workers.models.workers.user_path,
                        verbose_name="Фото",
                    ),
                ),
                (
                    "image_smol",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.workers.models.workers.user_path,
                        verbose_name="Фото маленькое",
                    ),
                ),
                (
                    "employee",
                    models.CharField(
                        choices=[
                            ("employee_current", "Сотрудник действующий"),
                            ("employee_fired", "Сотрудник уволенный"),
                            ("contractor_current", "Подрядчик действующий"),
                            ("contractor_fired", "Подрядчик уволенный"),
                            ("exploitation_current", "Эксплуатация действующий"),
                            ("exploitation_fired", "Эксплуатация уволенный"),
                            ("technician_current", "Наладчик действующий"),
                            ("technician_fired", "Наладчик уволенный"),
                        ],
                        default="employee_current",
                        max_length=30,
                        verbose_name="Сотрудник",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "ordering": ["pk"],
                "permissions": (
                    ("user_add", "Добавить."),
                    ("user_change", "Редактировать."),
                    ("user_delete", "Удалить."),
                    ("user_view", "Просмотреть."),
                ),
                "default_permissions": "",
            },
        ),
    ]
