# Generated by Django 4.2.7 on 2023-11-26 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="Отдел"),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Сокращенное название"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Структура. Отдел",
                "verbose_name_plural": "Структура. Отделы",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Subdivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="Управление/Подразделение",
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Сокращенное название"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Управление/Подразделение",
                "verbose_name_plural": "Управление/Подразделение",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Chief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Должность"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Сокращенное название"
                    ),
                ),
                (
                    "rights",
                    models.IntegerField(
                        default=0, unique=True, verbose_name="Уровень доступа"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auth.group",
                        verbose_name="Группы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Структура. Должность",
                "verbose_name_plural": "Структура. Должности",
                "ordering": ["rights"],
            },
        ),
    ]
