# Generated by Django 4.2.7 on 2024-10-10 19:14

import apps.workers.models.user_basic
import apps.workers.models.user_worker
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserBasic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("surname", models.CharField(max_length=60, verbose_name="Фамилия")),
                ("name", models.CharField(max_length=60, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(max_length=60, verbose_name="Отчество"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True, verbose_name="Телефон"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.workers.models.user_basic.user_path,
                        verbose_name="Аватарка",
                    ),
                ),
                (
                    "image_smol",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.workers.models.user_basic.user_path,
                        verbose_name="Аватарка маленькая",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("WORKER", "Сотрудник"),
                            ("WATCHER", "Наблюдатель"),
                            ("EXPLOITATION", "Эксплуатация"),
                            ("CUSTOMER", "Заказчик"),
                            ("SERVICEMAN", "Наладчик"),
                        ],
                        default="WATCHER",
                        max_length=13,
                        verbose_name="Тип пользователя",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Персонал"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Пользователь. Базовая.",
                "verbose_name_plural": "Пользователи. Базовая.",
                "ordering": ["pk"],
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="Chief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Должность"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Сокращенное название"
                    ),
                ),
                (
                    "rights",
                    models.IntegerField(
                        default=0, unique=True, verbose_name="Уровень доступа"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
                "ordering": ["-rights"],
                "permissions": (
                    ("Chief_add", "Должность. Добавить."),
                    ("Chief_change", "Должность. Редактировать."),
                    ("Chief_delete", "Должность. Удалить."),
                    ("Chief_view", "Должность. Просмотреть."),
                    ("Chief_permissions", "Должность. Права должности."),
                ),
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="Отдел"),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Сокращенное название"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Структура/Отдел",
                "verbose_name_plural": "Структура/Отделы",
                "ordering": ["pk"],
                "permissions": (
                    ("Department_add", "Отдел. Добавить."),
                    ("Department_change", "Отдел. Редактировать."),
                    ("Department_delete", "Отдел. Удалить."),
                    ("Department_view", "Отдел. Просмотреть."),
                ),
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="InformationMissing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Причина отсутствия"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#ffffff", max_length=7, verbose_name="Цвет"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
            ],
            options={
                "verbose_name": "Причина отсутствия на работе",
                "verbose_name_plural": "Причины отсутствия на работе",
                "ordering": ["name"],
                "permissions": (
                    (
                        "InformationMissing_add",
                        "Пользователь. Сотрудник. Причины отсутствия на работе. Добавить.",
                    ),
                    (
                        "InformationMissing_view",
                        "Пользователь. Сотрудник. Причины отсутствия на работе. Просмотреть.",
                    ),
                    (
                        "InformationMissing_delete",
                        "Пользователь. Сотрудник. Причины отсутствия на работе. Удалить.",
                    ),
                    (
                        "InformationMissing_change",
                        "Пользователь. Сотрудник. Причины отсутствия на работе. Редактировать.",
                    ),
                ),
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="InformationWeekendsHolidays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Дата")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Описание"),
                ),
                (
                    "work",
                    models.BooleanField(
                        default=False, verbose_name="Выходим на работу"
                    ),
                ),
                (
                    "work_time",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Время работы"
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация о выходных днях и праздниках",
                "verbose_name_plural": "Информация о выходных днях и праздниках",
                "ordering": ["date"],
                "permissions": (
                    (
                        "InformationWeekendsHolidays_add",
                        "Пользователь. Сотрудник. Информация о выходных днях и праздниках. Добавить.",
                    ),
                    (
                        "InformationWeekendsHolidays_view",
                        "Пользователь. Сотрудник. Информация о выходных днях и праздниках. Просмотреть.",
                    ),
                    (
                        "InformationWeekendsHolidays_delete",
                        "Пользователь. Сотрудник. Информация о выходных днях и праздниках. Удалить.",
                    ),
                    (
                        "InformationWeekendsHolidays_change",
                        "Пользователь. Сотрудник. Информация о выходных днях и праздниках. Редактировать.",
                    ),
                ),
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="OrganizationExploitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=40, verbose_name="Город"),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True, max_length=15, unique=True, verbose_name="ИНН"
                    ),
                ),
                (
                    "legal_address",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Юридический адрес"
                    ),
                ),
                (
                    "letter_address",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Адрес для корреспонденции",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, max_length=150, verbose_name="Сайт"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Эксплуатирующая организация",
                "verbose_name_plural": "Эксплуатирующие организации",
                "ordering": ["name"],
                "permissions": (
                    (
                        "organizationExploitation_add",
                        "Эксплуатирующая организация. Добавить.",
                    ),
                    (
                        "organizationExploitation_change",
                        "Эксплуатирующая организация. Редактировать.",
                    ),
                    (
                        "organizationExploitation_delete",
                        "Эксплуатирующая организация. Удалить.",
                    ),
                    (
                        "organizationExploitation_view",
                        "Эксплуатирующая организация. Просмотреть.",
                    ),
                ),
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="Subdivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="Управление/Подразделение",
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Сокращенное название"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Управление/Подразделение",
                "verbose_name_plural": "Управления/Подразделения",
                "ordering": ["pk"],
                "permissions": (
                    ("Subdivision_add", "Управление/Подразделение. Добавить."),
                    ("Subdivision_change", "Управление/Подразделение. Редактировать."),
                    ("Subdivision_delete", "Управление/Подразделение. Удалить."),
                    ("Subdivision_view", "Управление/Подразделение. Просмотреть."),
                ),
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="WorkerBasic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee",
                    models.CharField(
                        choices=[
                            ("employee_current", "Сотрудник действующий"),
                            ("employee_fired", "Сотрудник уволенный"),
                        ],
                        default="employee_current",
                        max_length=30,
                        verbose_name="Статус сотрудника",
                    ),
                ),
                (
                    "date_employment",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата трудоустройства"
                    ),
                ),
                (
                    "date_chief",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата в должности"
                    ),
                ),
                (
                    "employee_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата увольнения"
                    ),
                ),
                (
                    "number_ga",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Номер табеля"
                    ),
                ),
                (
                    "date_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "home_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Домашний адрес",
                    ),
                ),
                (
                    "home_metro",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ближайшее метро",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Мужской"), ("Female", "Женский")],
                        max_length=10,
                        verbose_name="Пол",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь. Сотрудник. Общая информация.",
                "verbose_name_plural": "Пользователь. Сотрудники. Общая информация.",
                "ordering": ["user"],
                "permissions": (
                    (
                        "WorkerBasic_his_change",
                        "Пользователи. Сотрудник. Общая информация. Самостоятельно. Редактировать. ",
                    ),
                    (
                        "WorkerBasic_department_change",
                        "Пользователи. Сотрудник. Общая информация. Проверка отдела. Редактировать. ",
                    ),
                    (
                        "WorkerBasic_subdivision_change",
                        "Пользователи. Сотрудник. Общая информация. Проверка управления. Редактировать.",
                    ),
                    (
                        "WorkerBasic_management_change",
                        "Пользователи. Сотрудник. Общая информация. Для руководства. Редактировать.",
                    ),
                    (
                        "WorkerBasic_department_view",
                        "Пользователи. Сотрудник. Общая информация. Проверка отдела. Просмотреть. ",
                    ),
                    (
                        "WorkerBasic_subdivision_view",
                        "Пользователи. Сотрудник. Общая информация. Проверка управления. Просмотреть.",
                    ),
                    (
                        "WorkerBasic_management_view",
                        "Пользователи. Сотрудник. Общая информация. Для руководства. Просмотреть.",
                    ),
                ),
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="WorkerClosed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_order_of_employment",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Приказ о трудоустройстве",
                    ),
                ),
                (
                    "organization_labor_contract",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Трудовой договор",
                    ),
                ),
                (
                    "passport_serial",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Паспорт Серия"
                    ),
                ),
                (
                    "passport_number",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Паспорт Номер"
                    ),
                ),
                (
                    "passport_passport_issued",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Паспорт Выдан",
                    ),
                ),
                (
                    "passport_passport_issued_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Паспорт Дата выдачи"
                    ),
                ),
                (
                    "passport_place_of_issue",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Паспорт Код подразделения",
                    ),
                ),
                (
                    "passport_registration",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Паспорт Место выдачи",
                    ),
                ),
                (
                    "passport_of_residence",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Паспорт Прописка",
                    ),
                ),
                (
                    "passport_scan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workers.models.user_worker.closed_path,
                        verbose_name="Паспорт скан",
                    ),
                ),
                (
                    "snils_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="СНИЛС номер",
                    ),
                ),
                (
                    "snils_scan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workers.models.user_worker.closed_path,
                        verbose_name="СНИЛС скан",
                    ),
                ),
                (
                    "inn_number",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Инн номер"
                    ),
                ),
                (
                    "inn_scan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workers.models.user_worker.closed_path,
                        verbose_name="Инн скан",
                    ),
                ),
                (
                    "archive_documents_employment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.workers.models.user_worker.closed_path,
                        verbose_name="Пакет документов при трудоустройстве",
                    ),
                ),
                (
                    "signature_example",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.workers.models.user_worker.closed_path,
                        verbose_name="Пример подписи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователи. Сотрудник. Закрытая информация.",
                "verbose_name_plural": "Пользователи. Сотрудники. Закрытая информация.",
                "ordering": ["pk"],
                "permissions": (
                    (
                        "WorkerClosed_his_change",
                        "Пользователи. Сотрудник. Закрытая информация. Самостоятельно. Редактировать. ",
                    ),
                    (
                        "WorkerClosed_department_change",
                        "Пользователи. Сотрудник. Закрытая информация. Проверка отдела. Редактировать. ",
                    ),
                    (
                        "WorkerClosed_subdivision_change",
                        "Пользователи. Сотрудник. Закрытая информация. Проверка управления. Редактировать.",
                    ),
                    (
                        "WorkerClosed_management_change",
                        "Пользователи. Сотрудник. Закрытая информация. Для руководства. Редактировать.",
                    ),
                    (
                        "WorkerClosed_department_view",
                        "Пользователи. Сотрудник. Закрытая информация. Проверка отдела. Просмотреть. ",
                    ),
                    (
                        "WorkerClosed_subdivision_view",
                        "Пользователи. Сотрудник. Закрытая информация. Проверка управления. Просмотреть.",
                    ),
                    (
                        "WorkerClosed_management_view",
                        "Пользователи. Сотрудник. Закрытая информация. Для руководства. Просмотреть.",
                    ),
                ),
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="WorkersMissing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateField(verbose_name="Дата начала отсутствия")),
                (
                    "date_end",
                    models.DateField(verbose_name="Дата окончание отсутствия"),
                ),
                (
                    "comments",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарии"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отсутствие сотрудника",
                "verbose_name_plural": "Отсутствие сотрудников",
                "ordering": ["pk"],
                "permissions": (
                    (
                        "WorkersMissing_department_add",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Проверка отдела. Добавить.",
                    ),
                    (
                        "WorkersMissing_subdivision_add",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Проверка управления. Добавить.",
                    ),
                    (
                        "WorkersMissing_management_add",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Для руководства. Добавить.",
                    ),
                    (
                        "WorkersMissing_his_add",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Самостоятельно. Добавить.",
                    ),
                    (
                        "WorkersMissing_department_change",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Проверка отдела. Редактировать.",
                    ),
                    (
                        "WorkersMissing_subdivision_change",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Проверка управления. Редактировать.",
                    ),
                    (
                        "WorkersMissing_management_change",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Для руководства. Редактировать.",
                    ),
                    (
                        "WorkersMissing_his_change",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Самостоятельно. Редактировать.",
                    ),
                    (
                        "WorkersMissing_department_delete",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Проверка отдела. Удалить.",
                    ),
                    (
                        "WorkersMissing_subdivision_delete",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Проверка управления. Удалить.",
                    ),
                    (
                        "WorkersMissing_management_delete",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Для руководства. Удалить.",
                    ),
                    (
                        "WorkersMissing_his_delete",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Самостоятельно. Удалить.",
                    ),
                    (
                        "WorkersMissing_department_view",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Проверка отдела. Просмотреть.",
                    ),
                    (
                        "WorkersMissing_subdivision_view",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Проверка управления. Просмотреть.",
                    ),
                    (
                        "WorkersMissing_management_view",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Для руководства. Просмотреть.",
                    ),
                    (
                        "WorkersMissing_his_view",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Самостоятельно. Просмотреть.",
                    ),
                ),
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="WorkersMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_departure", models.DateField(verbose_name="Дата выезда")),
                (
                    "date_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата начала работы"
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончание работы"
                    ),
                ),
                ("date_arrival", models.DateField(verbose_name="Дата прибытия")),
                (
                    "status",
                    models.CharField(
                        choices=[("FINAL", "Итоговая"), ("PLANNING", "Планируемая")],
                        default="FINAL",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Командировка сотрудника",
                "verbose_name_plural": "Командировка сотрудников",
                "ordering": ["pk"],
                "permissions": (
                    (
                        "WorkersMission_department_add",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Проверка отдела. Добавить.",
                    ),
                    (
                        "WorkersMission_subdivision_add",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Проверка управления. Добавить.",
                    ),
                    (
                        "WorkersMission_management_add",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Для руководства. Добавить.",
                    ),
                    (
                        "WorkersMission_his_add",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Самостоятельно. Добавить.",
                    ),
                    (
                        "WorkersMission_department_change",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Проверка отдела. Редактировать.",
                    ),
                    (
                        "WorkersMission_subdivision_change",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Проверка управления. Редактировать.",
                    ),
                    (
                        "WorkersMission_management_change",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Для руководства. Редактировать.",
                    ),
                    (
                        "WorkersMission_his_change",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Самостоятельно. Редактировать.",
                    ),
                    (
                        "WorkersMission_department_delete",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Проверка отдела. Удалить.",
                    ),
                    (
                        "WorkersMission_subdivision_delete",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Проверка управления. Удалить.",
                    ),
                    (
                        "WorkersMission_management_delete",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Для руководства. Удалить.",
                    ),
                    (
                        "WorkersMission_his_delete",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Самостоятельно. Удалить.",
                    ),
                    (
                        "WorkersMission_department_view",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Проверка отдела. Просмотреть.",
                    ),
                    (
                        "WorkersMission_subdivision_view",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Проверка управления. Просмотреть.",
                    ),
                    (
                        "WorkersMission_management_view",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Для руководства. Просмотреть.",
                    ),
                    (
                        "WorkersMission_his_view",
                        "Пользователи. Сотрудник. Отсутствие сотрудников. Самостоятельно. Просмотреть.",
                    ),
                    (
                        "WorkersPlannig_department_view",
                        "Пользователи. Сотрудник. Планирование работ. Проверка отдела. Просмотреть.",
                    ),
                    (
                        "WorkersPlannig_subdivision_view",
                        "Пользователи. Сотрудник. Планирование работ. Проверка управления. Просмотреть.",
                    ),
                    (
                        "WorkersPlannig_management_view",
                        "Пользователи. Сотрудник. Планирование работ. Для руководства. Просмотреть.",
                    ),
                    (
                        "WorkersPlannig_his_view",
                        "Пользователи. Сотрудник. Планирование работ. Самостоятельно. Просмотреть.",
                    ),
                ),
                "default_permissions": "",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "userbasic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь. Заказчик.",
                "verbose_name_plural": "Пользователь. Заказчики.",
                "ordering": ["pk"],
                "permissions": (
                    ("UserCustomer_add", "Пользователь. Заказчик. Добавить."),
                    ("UserCustomer_change", "Пользователь. Заказчик. Редактировать."),
                    ("UserCustomer_delete", "Пользователь. Заказчик. Удалить."),
                    ("UserCustomer_view", "Пользователь. Заказчик. Просмотреть."),
                ),
                "default_permissions": "",
            },
            bases=("workers.userbasic",),
        ),
        migrations.CreateModel(
            name="Exploitation",
            fields=[
                (
                    "userbasic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь. Эксплуатация.",
                "verbose_name_plural": "Пользователи. Эксплуатация.",
                "ordering": ["pk"],
                "default_permissions": "",
            },
            bases=("workers.userbasic",),
        ),
        migrations.CreateModel(
            name="Serviceman",
            fields=[
                (
                    "userbasic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь. Наладчик.",
                "verbose_name_plural": "Пользователи. Наладчики.",
                "ordering": ["pk"],
                "permissions": (
                    ("UserServiceman_add", "Пользователи. Наладчики. Добавить."),
                    (
                        "UserServiceman_change",
                        "Пользователи. Наладчики. Редактировать.",
                    ),
                    ("UserServiceman_delete", "Пользователи. Наладчики. Удалить."),
                    ("UserServiceman_view", "Пользователи. Наладчики. Просмотреть."),
                ),
                "default_permissions": "",
            },
            bases=("workers.userbasic",),
        ),
        migrations.CreateModel(
            name="Watcher",
            fields=[
                (
                    "userbasic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь. Наблюдатель.",
                "verbose_name_plural": "Пользователи. Наблюдатели.",
                "ordering": ["pk"],
                "permissions": (
                    ("UserWatcher_add", "Пользователи. Наблюдатель. Добавить."),
                    ("UserWatcher_change", "Пользователи. Наблюдатель. Редактировать."),
                    ("UserWatcher_delete", "Пользователи. Наблюдатель. Удалить."),
                    ("UserWatcher_view", "Пользователи. Наблюдатель. Просмотреть."),
                ),
                "default_permissions": "",
            },
            bases=("workers.userbasic",),
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "userbasic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь. Сотрудник.",
                "verbose_name_plural": "Пользователи. Сотрудники.",
                "ordering": ["pk"],
                "permissions": (
                    ("Worker_add", "Пользователи. Сотрудник. Добавить."),
                    ("Worker_view", "Пользователи. Сотрудник. Просмотреть."),
                    (
                        "Worker_his_change",
                        "Пользователи. Сотрудник. Самостоятельно. Редактировать. ",
                    ),
                    (
                        "Worker_department_change",
                        "Пользователи. Сотрудник. Проверка отдела. Редактировать. ",
                    ),
                    (
                        "Worker_subdivision_change",
                        "Пользователи. Сотрудник. Проверка управления. Редактировать. ",
                    ),
                    (
                        "Worker_management_change",
                        "Пользователи. Сотрудник. Для руководства. Редактировать. ",
                    ),
                    (
                        "Worker_department_change_password",
                        "Пользователи. Сотрудник. Проверка отдела. Обновить пароль. ",
                    ),
                    (
                        "Worker_subdivision_change_password",
                        "Пользователи. Сотрудник. Проверка управления. Обновить пароль.",
                    ),
                    (
                        "Worker_management_change_password",
                        "Пользователи. Сотрудник. Для руководства. Обновить пароль.",
                    ),
                    (
                        "Worker_department_change_permission",
                        "Пользователи. Сотрудник. Проверка отдела. Права доступа.",
                    ),
                    (
                        "Worker_subdivision_change_permission",
                        "Пользователи. Сотрудник. Проверка управления. Права доступа.",
                    ),
                    (
                        "Worker_management_change_permission",
                        "Пользователи. Сотрудник. Для руководства. Права доступа.",
                    ),
                ),
                "default_permissions": "",
            },
            bases=("workers.userbasic",),
        ),
        migrations.CreateModel(
            name="WorkersWeekendWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата выхода")),
                (
                    "planning",
                    models.TextField(blank=True, verbose_name="Планирование работ"),
                ),
                (
                    "hours_working",
                    models.FloatField(
                        blank=True, default=-1.0, verbose_name="Отработанное время"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workers.workerbasic",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работа в выходные в офисе.",
                "verbose_name_plural": "Работа в выходные в офисе.",
                "ordering": ["pk"],
                "permissions": (
                    (
                        "WorkersWeekendWork_department_add",
                        "Пользователи. Сотрудник. Работа в выходные в офисе. Проверка отдела. Добавить.",
                    ),
                    (
                        "WorkersWeekendWork_subdivision_add",
                        "Пользователи. Сотрудник. Работа в выходные в офисе. Проверка управления. Добавить.",
                    ),
                    (
                        "WorkersWeekendWork_management_add",
                        "Пользователи. Сотрудник. Работа в выходные в офисе. Для руководства. Добавить.",
                    ),
                    (
                        "WorkersWeekendWork_his_add",
                        "Пользователи. Сотрудник. Работа в выходные в офисе. Самостоятельно. Добавить.",
                    ),
                    (
                        "WorkersWeekendWork_department_change",
                        "Пользователи. Сотрудник. Работа в выходные в офисе. Проверка отдела. Редактировать.",
                    ),
                    (
                        "WorkersWeekendWork_subdivision_change",
                        "Пользователи. Сотрудник. Работа в выходные в офисе. Проверка управления. Редактировать.",
                    ),
                    (
                        "WorkersWeekendWork_management_change",
                        "Пользователи. Сотрудник. Работа в выходные в офисе. Для руководства. Редактировать.",
                    ),
                    (
                        "WorkersWeekendWork_his_change",
                        "Пользователи. Сотрудник. Работа в выходные в офисе. Самостоятельно. Редактировать.",
                    ),
                    (
                        "WorkersWeekendWork_department_delete",
                        "Пользователи. Сотрудник. Работа в выходные в офисе. Проверка отдела. Удалить.",
                    ),
                    (
                        "WorkersWeekendWork_subdivision_delete",
                        "Пользователи. Сотрудник. Работа в выходные в офисе. Проверка управления. Удалить.",
                    ),
                    (
                        "WorkersWeekendWork_management_delete",
                        "Пользователи. Сотрудник. Работа в выходные в офисе. Для руководства. Удалить.",
                    ),
                    (
                        "WorkersWeekendWork_his_delete",
                        "Пользователи. Сотрудник. Работа в выходные в офисе. Самостоятельно. Удалить.",
                    ),
                    (
                        "WorkersWeekendWork_department_view",
                        "Пользователи. Сотрудник. Работа в выходные в офисе. Проверка отдела. Просмотреть.",
                    ),
                    (
                        "WorkersWeekendWork_subdivision_view",
                        "Пользователи. Сотрудник. Работа в выходные в офисе. Проверка управления. Просмотреть.",
                    ),
                    (
                        "WorkersWeekendWork_management_view",
                        "Пользователи. Сотрудник. Работа в выходные в офисе. Для руководства. Просмотреть.",
                    ),
                    (
                        "WorkersWeekendWork_his_view",
                        "Пользователи. Сотрудник. Работа в выходные в офисе. Самостоятельно. Просмотреть.",
                    ),
                ),
                "default_permissions": "",
            },
        ),
    ]
