# Generated by Django 4.2.7 on 2024-10-10 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("workers", "0001_initial"),
        ("workobjects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workersmission",
            name="organizations_objects",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="workobjects.organizationsobjects",
                verbose_name="Объект командировки",
            ),
        ),
        migrations.AddField(
            model_name="workersmission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="workers.workerbasic",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AddField(
            model_name="workersmissing",
            name="information_missing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="workers.informationmissing",
                verbose_name="Причина отсутствия",
            ),
        ),
        migrations.AddField(
            model_name="workersmissing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="workers.workerbasic",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AddField(
            model_name="workerbasic",
            name="actual_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actual_department",
                to="workers.department",
                verbose_name="Фактический отдел",
            ),
        ),
        migrations.AddField(
            model_name="workerbasic",
            name="actual_subdivision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actual_subdivision",
                to="workers.subdivision",
                verbose_name="Фактическое Управление",
            ),
        ),
        migrations.AddField(
            model_name="workerbasic",
            name="chief",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="workers.chief",
                verbose_name="Должность",
            ),
        ),
        migrations.AddField(
            model_name="workerbasic",
            name="organization_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_department",
                to="workers.department",
                verbose_name="Отдел в организации",
            ),
        ),
        migrations.AddField(
            model_name="workerbasic",
            name="organization_subdivision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_subdivision",
                to="workers.subdivision",
                verbose_name="Управление в организации",
            ),
        ),
        migrations.AddField(
            model_name="chief",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="auth.group",
                verbose_name="Группы",
            ),
        ),
        migrations.AddField(
            model_name="userbasic",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="userbasic",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="workerclosed",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="workers.worker",
                verbose_name="ФИО",
            ),
        ),
        migrations.AddField(
            model_name="workerbasic",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="workers.worker",
                verbose_name="ФИО",
            ),
        ),
    ]
